name: fastapi_sample_DO
region: nyc
services:
- environment_slug: python
#- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: mallikmatiullah/fastapi_sample_DO
http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: fastapi_sample_DO
  routes:
  - path: /
  run_command: gunicorn --worker-tmp-dir /dev/shm --config gunicorn.config.py app:app 
